server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_db:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerslogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            log: log
            stack_namespace: attrs."com.docker.stack.namespace"
            swarm_service_name: attrs."com.docker.swarm.service.name"
            swarm_task_name: attrs."com.docker.swarm.task.name"
      - labels:
          stack_namespace:
          swarm_service_name:
          swarm_task_name:
      - output:
          source: log
